name: Challenge Practice 

on: push

jobs: 
  print_name:
  # Changed to a standard runner name
    runs-on: ubuntu-latest


    steps:
    #THIS IS THE CRITICAL THING FOR RUNNING SCRIPTS IN THE PIPELINE
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Print name
        run: echo "My name is Soumyaraj Debnath"

      - name: Print Current Date
        run: python3 scripts/curr_date.py

      - name: Print Status
        run: echo "Test pipeline working"

